version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nqve-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - nqve-pgdata:/var/lib/postgresql/data
    networks:
      - nqve-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: nqve-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - nqve-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nqve-back:latest
    container_name: nqve-back

    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    ports:
      - "9000:8080"
    networks:
      - nqve-net

volumes:
  nqve-pgdata:
networks:
  nqve-net: