server :
  port : 8080

spring :
  datasource:
     url:
      jdc:postgresql://localhost:5432/igvibe
     username : postgres
     password : password
  jpa :
      hibernate:
        ddl-auto : update
      show-sql : true
  data :
     redis :
      host : localhost
      port: 6379