server :
  port : 8080

spring :
  datasource:
     url:
      jdbc:postgresql://localhost:5432/
     username : postgres
     password : ghfkddl1!
  jpa :
      hibernate:
        ddl-auto : update
      show-sql : true
  data :
     redis :
      host : localhost
      port: 6379