spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nqve_db
    username: nqve_user
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
